### ISSUE TITLE
Open Containing Folder is not opening the right directory

### ISSUE THREAD

**Issue by SrBrahma** [SrBrahma/GitHub-Repository-Manager#13]
Edit: It's a VS Code problem. Created an issue on their repository: https://github.com/microsoft/vscode/issues/105666.

For now, removed the Open Containing Directory Icon next to the cloned repository.

**Comment by SrBrahma** [comment]
Strange, happened twice but not happening again.

**Comment by AndrewLaganaro** [comment]
Olá @SrBrahma , quando eu tento abrir o repositório que ja dei clone, o Vscode não consegue identificar o endereço da pasta
Nas configurações do Vscode eu coloquei: 
`"git.defaultCloneDirectory":"C:\\Users\\Andrew\\Desenvolvimento"`
Ele identifica um repositório chamado "Dev"(sob o endereço: `"C:\\Users\\Andrew\\Desenvolvimento\\Dev"`) mas ao clicar para abrir a pasta consta o erro

"Não foi possível abrir 'Dev': `Unable to resolve resource C:%5CUsers%5CAndrew%5CDesenvolvimento%5CDev.`"
![image](https://user-images.githubusercontent.com/45211616/91642488-1c120a80-ea02-11ea-98e4-0c548f29771f.png)
Na barra lateral ele não exibe o "C:", apenas começa a partir do "\Users", o que é bem estranho:
![image](https://user-images.githubusercontent.com/45211616/91642496-2c29ea00-ea02-11ea-988a-5d787c7e7e9b.png)
No entanto ao abrir a pasta normalmente pelo "Abrir Pasta" do Vscode, não ocorre nenhum erro:
![image](https://user-images.githubusercontent.com/45211616/91642512-4a8fe580-ea02-11ea-8e89-75ce691e6f14.png)
Todas as configurações que determinei para a extensão e para o git são apenas estas:
![image](https://user-images.githubusercontent.com/45211616/91642564-c38f3d00-ea02-11ea-85f9-e0cbf9992812.png)

Isso também ocorre em outros computadores.

Existe uma solução para o problema? Obrigado!

**Comment by SrBrahma** [comment]
Vou investigar :)

**Comment by SrBrahma** [comment]
Chega a aparecer a lista dos repositórios clonados no menu lateral da extensão?

**Comment by AndrewLaganaro** [comment]
Sim, aparece. No momento só tenho um, e ele está como privado. Não sei se faz diferença também... Mas aparece.
E pra constar, também tenho a extensão Project Manager, que aponta pra mesma pasta:
`"projectManager.git.baseFolders": ["C:\\Users\\Andrew\\Desenvolvimento"],`
São as únicas extensões que apontam ou mexem com essa pasta, caso ajude

![image](https://user-images.githubusercontent.com/45211616/91642655-824b5d00-ea03-11ea-8aa7-c44fe43ec899.png)

**Comment by SrBrahma** [comment]
@AndrewLaganaro , publiquei uma versão nova que deve ter resolvido esse problema no Windows. Reabra o VsCode que ele deve atualizar automaticamente a extensão. Veja na seção de extensões se ele foi atualizado para a versão 0.5.1, e se sim, deve aparecer que é necessário reabrir mais uma vez o VsCode, e me conta se resolveu :)

**Comment by AndrewLaganaro** [comment]
Olá, ele está na 0.5.1 mas o problema continua ocorrendo. Agora porém, ele não manda mais o aviso de erro ao ler o endereço da pasta, o erro simplesmente acontece sem notificação

foto do teste de agora pouco:
![image](https://user-images.githubusercontent.com/45211616/91645523-0a3d6100-ea1c-11ea-8e62-781a20e378f1.png)

**Comment by SrBrahma** [comment]
Você está tentando abrir a pasta pelo botão direito ou pelo ícone do lado do nome do repositório? Tente pelo botão direito e me diga se acontece também.

**Comment by AndrewLaganaro** [comment]
Bem, tanto no ícone "open in new window" quanto no "open" no botão direito quanto clicando duas vezes sobre o nome do repositório gera o mesmo resultado do erro

**Comment by SrBrahma** [comment]
Creio que fixei o problema na versão já disponível 0.6.0. Muito obrigado mesmo por apontar o problema. Fico até mal pensando em quantos usuários de Windows tiveram esse mesmo problema.

**Comment by AndrewLaganaro** [comment]
Deu certo!
Repositórios abrem normalmente ao dar dois cliques ou no ícone de nova janela
![image](https://user-images.githubusercontent.com/45211616/91666056-52b65680-ead0-11ea-80e3-2b651bb70d41.png)
![image](https://user-images.githubusercontent.com/45211616/91666065-65c92680-ead0-11ea-92a4-4bdd2dd66a2b.png)
