### ISSUE TITLE
GitHub Pages don't go to the list of repos cloned

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [SrBrahma/GitHub-Repository-Manager#21]
No matter how I go about it my GitHub Pages repo never goes to the list of cloned sites and if I click on it in the Not Cloned list then it says it's already cloned, if it's cloned already which is to be expected.

I love this extension though so I hope this gets fixed but it's not a deal breaker! :)

**Comment by SrBrahma** [comment]
Can you record a video of it so I can understand the issue better?

Thanks for the issue!

**Comment by xCONFLiCTiONx** [comment]
I don't have the software of hardware for that but I'll do my best to explain a bit better.

I have cloned my GitHub Pages website repo 'xCONFLiCTiONx.github.io' as you can see in the screenshot but it isn't showing in the 'Cloned Repositories' section.

I have tried cloning through your extension and I've tried cloning from the terminal while closed and I've tried cloning from the terminal while opened to see if it would ever show and it never will.

![Screenshot 2021-02-02 091907](https://user-images.githubusercontent.com/12835195/106621500-3e233200-6538-11eb-93c7-d961ddcf6be4.jpg)

**Comment by SrBrahma** [comment]
I see. Can you paste here the `.git/config` content? Also, what is your OS? Tomorrow I will also fork your project to test it here.

**Comment by xCONFLiCTiONx** [comment]
`.git/config`
`[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[remote "origin"]
	url = https://github.com/xCONFLiCTiONx/xCONFLiCTiONx.github.io.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
`
OS: Windows 10 x64 20H2 19042.746

Thanks for looking into this!

**Comment by SrBrahma** [comment]
Related commit: https://github.com/SrBrahma/GitHub-Repository-Manager/commit/d6aa48e44f480f078818e4b17f5ad184e96f60c1

**Comment by SrBrahma** [comment]
Extension updated to 0.6.1 via https://github.com/SrBrahma/GitHub-Repository-Manager/commit/443f8f239f9516a3ec8514037c7250ef989aca93.

Be sure that the installed extension is now at the version 0.6.1 (look it at the extensions tab in your vscode) and tell me if it has been fixed for you!

**Comment by xCONFLiCTiONx** [comment]
It's fixed! Thank you! You're awesome dude! That was really fast!
