### ISSUE TITLE
When creating a repository, allow choosing to publish to an organization

### ISSUE THREAD

**Issue by DillonSadofsky** [SrBrahma/GitHub-Repository-Manager#23]
I found this extension today when searching for a vanilla way to publish a newly created repo to github under an organization I'm an owner of.  Devs in my team put our production private repos in the company org, but when I click on the Create Repository button in your extension, no matter what I try, the newly created repo is under my personal account instead of the organization.  This makes it so that I have to go to the github website and transfer ownership.  This is annoying and why I grabbed this extension.

The extension correctly recognizes that I'm part of these organizations and is capable of displaying cloned and uncloned repos in them.  I tried entering a repo name of "the organization name/repo name" and that didn't seem to work, it just turned it into a personal repo named "the-organization-name-repo-name".  I also tried 'selecting an org' in the repo tree before hitting plus and that didn't help.

My suggestion would be:
1. If the user starts creating a repo, if they are part of any orgs, show a pop down at the top asking which org.  This could come right before asking for Repository Name. (github desktop essentially has a dropdown like this in their UI)
2. Also, add a + that appears when you hover over an org in the repo tree.  If you click that one, it should go through the normal add repo flow with that org automatically selected.

Anyway, if I'm missing some way to make this extension publish to an org instead of my personal account, I'd love to hear it.  Currently I don't publish any projects to the personal account I'm logged in as, only my org, so I'd even accept a settings.json override that is 'default organization to publish to' or whatever.

**Comment by DillonSadofsky** [comment]
I just wanted to add that the vs code built in "Publish to github" button seems to have the same shortcoming, which is the reason I grabbed this extension.  I figured it'd allow me to push new projects up to my org without having to go to github desktop or the web interface.

**Comment by SrBrahma** [comment]
Nice! Will implement it. But, may take up to a month until I have the time do do so.

**Comment by DillonSadofsky** [comment]
Understood.  IDK if you use the github cli or not, but I think these docs on "gh repo create" suggest just putting the <Organization name>/<repo name> should work:
https://cli.github.com/manual/gh_repo_create

**Comment by SrBrahma** [comment]
I didn't know about this GitHub cli, good to know! But, it would require for the extension users to have it installed in order to the extension to use it in the user machine.

I already have an idea on how to do it with the current system, shouldn't be too hard. Certainly in a day I can do it. Probably it will require another permission from OAuth/Token, but won't be an issue.

**Comment by DillonSadofsky** [comment]
Makes sense.  I've been exploring the best way to publish org repos and I came across that, so I figured I'd post it just in case it was useful.

I definitely appreciate your attention.  I think with this feature, the extension will be very useful for people like me who want to clone/publish into orgs.  I like the ability to see all the repos in the org to clone.  I was honestly pretty surprised that vs code itself doesn't have a way to choose an org while publishing to github in their source control area.

**Comment by SrBrahma** [comment]
@DillonSadofsky , sorry for taking some months more than I expected. I got a little busy with some other projects.

However, your request is finally done! I have nicely integrated it with the also new feature, the #2. If the user is a member of an organization that allows him to create repositories, it will be asked when `creating a repository` or `creating a repository for current files`, before the repository name input, where the new repository should be created, if it's for the user himself of for one of those organizations.

About your second suggestion,

> 2. Also, add a + that appears when you hover over an org in the repo tree. If you click that one, it should go through the normal add repo flow with that org automatically selected.

I ain't sure about it. I will think more about it with an open heart, but for now, I won't implement it. Maybe would pollute and complicate too much.
