### ISSUE TITLE
Button Next to a Repository to Open It in Github

### ISSUE THREAD

**Issue by hediet** [SrBrahma/GitHub-Repository-Manager#3]
It would be cool if this area:

![image](https://user-images.githubusercontent.com/2931520/81988729-3b944b80-963c-11ea-8ee3-d69e20f4615d.png)

could be used to show a button that opens the repository on github if clicked.

Like in git lense:

![image](https://user-images.githubusercontent.com/2931520/81988853-70a09e00-963c-11ea-9e21-6b58d3d318b5.png)

**Comment by SrBrahma** [comment]
I fear that it maybe would make the visual a little polluted, and there is already a right click option to open the GitHub page...

I could make a setting to enable / disable this.

Do you think it should be better be enabled by default?
What commands do you think there should be?

Thanks for the idea!

**Comment by hediet** [comment]
Oh, I did not try to do a right click :D Hmm, I think I would still prefer the button over the context menu (if configurable, then show them by default). The context menu is hard to find and gitlens is also using buttons.

**Comment by SrBrahma** [comment]
Probably tomorrow I will add it ;)

**Comment by SrBrahma** [comment]
[Added!](https://github.com/SrBrahma/GitHub-Repository-Manager/blob/master/CHANGELOG.md#030---may-15-2020)

Will implement your another idea another day.

:)
