### ISSUE TITLE
Error when cloning a repo

### ISSUE THREAD

**Issue by fslef** [SrBrahma/GitHub-Repository-Manager#33]
Hello,

I run into this issue when I try to clone a repo:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/23463958/146453684-76b9908c-cf06-4126-89d4-1b92cf730040.png">

This is my first try, I never used this extension before.

Could you help me to troubleshoot this issue ?

**Comment by SrBrahma** [comment]
Hi @fslef ! Is the repository in question public? Did you try it with other repositories?

**Comment by fslef** [comment]
I tried both, private and public repo, same behavior. But I need to clarify one point.

The error I'm facing is on MacOS system.
From Windows, same configuration same repo, I have no issues.

**Comment by SrBrahma** [comment]
I am also having this issue now, no idea why yet. Will look into it soon.

**Comment by SrBrahma** [comment]
Hi, seems that I fixed it.

I am using `git remote show <remoteUrl>` inside the just `git init` directory and parsing its stdout output to get the repo HEAD. It worked when the output was in English, but when in other languages it wouldn't work. I changed the regex to get it and hopefully now it shall work in other cases.

Also, I've added the stdout to the error message you've got (and fixed the "haven't" to "hasn't" lol), so if you or someone else still has this issue, I will only need to change the regex to support the user language that it's failing.

Also, this didn't happened before on Prod for me. Maybe there was a git update that added my language to it. I still have no idea on why it didn't happen on Dev but only on Prod yesterday.

Sorry for the first bad experience you've had and I ask if you can give it another try and tell me if it's now working ;)

**Comment by SrBrahma** [comment]
I am closing it now as it is probably fixed. If it still happening for you or someone else, I ask to send here the error message, now improved.
