### ISSUE TITLE
Cant not login Github account

### ISSUE THREAD

**Issue by ttsoares** [SrBrahma/GitHub-Repository-Manager#38]
Issue Type: <b>Bug</b>

1) Install Codium
2) Install GitHub Repo Manag
3) Click extension icon
4)  Click 'Login with your github account'
5) Paste your token in the form above
6) Error: Network connection 

In the Linux xterm i can use git push with my credentials normally.

Extension version: 1.3.3
VS Code version: VSCodium 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-04T09:01:50.498Z)
OS version: Linux x64 5.4.0-100-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2388)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.66GB (0.59GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by SrBrahma** [comment]
Hi! I haven't tested this extension with Codium. Do you have a way to test it with actual VSCode?

I've just tested the SignIn and it's working fine here.

**Comment by ttsoares** [comment]
I do not intend to install VSCode in my systems.

There is no Git extension able to login at Github with Codium. It is not
just yours that fails...

It is not my firewall neither my Pihole as form the Bash Git is working
fine.

Em sex., 4 de mar. de 2022 às 15:59, Henrique Bruno <
***@***.***> escreveu:

**Comment by SrBrahma** [comment]
I understand. I googled about it and found those that may help you.

https://github.com/VSCodium/vscodium/issues/401#issuecomment-631502370
https://github.com/microsoft/vscode-pull-request-github/issues/1778#issuecomment-629743423

**Comment by ttsoares** [comment]
Already tried those with no effect.

Will fix this with Atom.  Write in Codion and manage versions with Atom.

Em seg., 7 de mar. de 2022 às 17:10, Henrique Bruno <
***@***.***> escreveu:

**Comment by SrBrahma** [comment]
@adirz do you also use Codium?

**Comment by adirz** [comment]
@SrBrahma yes. but it happens for all github logins, so I might need a more general help 😮‍💨
