### ISSUE TITLE
Support Organization Repositories

### ISSUE THREAD

**Issue by dayyeung** [SrBrahma/GitHub-Repository-Manager#4]
If I am not mistaken this is currently not supported.
This extension looks really nice, but it would only be useful for me if this is supported.

**Comment by SrBrahma** [comment]
I will look into it.

**Comment by SrBrahma** [comment]
I am currently awaiting a GitHub answer to a question that I made to them, about possibly a bug with the GitHub v4 api.

A more detailed explanation, maybe for future references:

I can fetch the organizations repositories with basic and safe authorizations using the v3 api. But, this recourse in is experimental and may be removed (https://developer.github.com/v3/repos/#list-organization-repositories).

I achieved to make it work in v4, but required a full and very unsafe access to the organizations.

They will either fix it in v4 or tell me it won't be possible.

**Comment by jonathan-fielding** [comment]
Ok @dayyeung and @SrBrahma I have been attempting to make this work and have a branch where it works for personal access token https://github.com/SrBrahma/GitHub-Repository-Manager/pull/10

**Comment by jonathan-fielding** [comment]
@dayyeung looks like the PR to add this functionality is almost there https://github.com/SrBrahma/GitHub-Repository-Manager/pull/10

**Comment by SrBrahma** [comment]
Done!
