### ISSUE TITLE
Cloning fails: 'git remote show <remoteUrl>' hasn't returned a HEAD branch!

### ISSUE THREAD

**Issue by lo-ca** [SrBrahma/GitHub-Repository-Manager#42]
This is an issue in line with #33 ad #35. The root of the problem is, that HEAD itself gets localized (even though I'm purposefully keeping VS Code in English, but that is another issue and you could easily argue about expectations here). Probably I should code as another user with locale set to C.

As you can see below "HEAD" is called "Hauptbranch" (which isn't even proper German btw.), so your regex doesn't work. Also hard-coding the separator may or may not cause issues with yet another locale. Is it an idea to
1. either directly grab the 4th line of the output or the first line not matching an URL and then
2. accepting everything after the last whitespace as HEAD in exchange of the separator, 
instead of having a single regex causing issues with one locale after the other?

--
git remote show https://github.com/SrBrahma/GitHub-Repository-Manager.git 
* Remote-Repository https://github.com/SrBrahma/GitHub-Repository-Manager.git
  URL zum Abholen: https://github.com/SrBrahma/GitHub-Repository-Manager.git
  URL zum Versenden: https://github.com/SrBrahma/GitHub-Repository-Manager.git
  Hauptbranch: main
  Lokale Referenz konfiguriert für 'git push':
    main versendet nach main (aktuell)

**Comment by SrBrahma** [comment]
Thanks for the detailed issue!

I will fix it asap.

**Comment by SrBrahma** [comment]
HI @lo-ca! I added your suggestion in 1.5.1 via https://github.com/SrBrahma/GitHub-Repository-Manager/commit/a7c10e618fa7c25d4ee170771afb017c789025b6. It works and probably is the best solution, however I still am somewhat afraid that the output may be different if an additional info is printed before the HEAD line.

**Comment by lo-ca** [comment]
This was quick.Thank you. I'll give it a try, when you release v1.5.1.

Having to parse the output of command line tools is never the most welcome job - especially when localization comes into play.

**Comment by SrBrahma** [comment]
It's already available!
