### ISSUE TITLE
SSH cloned repositories not found 

### ISSUE THREAD

**Issue by jonathan-fielding** [SrBrahma/GitHub-Repository-Manager#8]
Looks like SSH cloned repositories are not found when it looks locally, to fix this the plugin should parse the urls into a standard format so it can compare the GitHub urls together

**Comment by jonathan-fielding** [comment]
Note: I am looking at fixing this now

**Comment by SrBrahma** [comment]
I never cloned with SSH, so I don't know the format that it appears when running 'git remove -v'. You may check the code of the cloned repos in src/Repository/searchClonedRepos.ts .
Maybe you can check if the result is in the SSH format, and add a regex to it to check

**Comment by SrBrahma** [comment]
I never cloned with SSH, so I don't know the format that it appears when running 'git remove -v'. You should check the code of the cloned repos in src/Repository/searchClonedRepos.ts .

Maybe you can check if the remote result is in the SSH format, and add a regex to it to compare the remotes URL

**Comment by jonathan-fielding** [comment]
there is so many different formats for git urls that I am just using a library that handles all of them lol, PR will be ready soon

**Comment by jonathan-fielding** [comment]
PR raised 🤗

**Comment by SrBrahma** [comment]
Going to test it, accept and deploy if ok (I forgot that I had to deploy it with vsce lol*) . Many thanks! I really appreciate it! ;)

* Do you know how to set up to automatically deploy the extension on repository master changes? I saw there was a way on VsCode docs some time ago, but I am not finding it.

**Comment by jonathan-fielding** [comment]
👍

**Comment by SrBrahma** [comment]
Deployed and working ;)
